context:
  prefix: full_default
  data: singlecell_postprocessed
  n_repeat: 3
  n_threads: 1
experiments:
  # -
  #   lang: python
  #   algorithm: cor_corrcoef
  # -
  #   lang: python
  #   algorithm: cor_matrix_symmetrical_nocopy
  -
    lang: julia
    algorithm: cor_cor
  # R doesn't finish within 24h ... doesn't seem to be true anymore with R 4.0
  -
    lang: r
    algorithm: cor_cor
