context:
  prefix: full_default
  data: cancer_postprocessed_nonegatives_dropduplicates_sample-0.50
  n_repeat: 10
  n_threads: 1
experiments:
  -
    lang: python
    algorithm: cor_corrcoef
  -
    lang: python
    algorithm: cor_matrix_symmetrical_nocopy
  # julia doesn't finish for some reason ... previously it did I think ... seems to work again
  -
    lang: julia
    algorithm: cor_cor
  # R doesn't finish within 24h ... doesn't seem to be true anymore with R 4.0
  -
    lang: r
    algorithm: cor_cor
