context:
  prefix: topk_default
  data: (cancer_postprocessed_nonegatives_dropduplicates_sample-1.00).*
  k_ratio: 0.001
  threshold: 0.9
  n_repeat: 3
  n_threads: 1
  python:
    memory_backend: "psutil" 
experiments:
  -
    lang: python
    algorithm: topk_balltree_combined_tree_optimized_parallel_64
  -
    lang: python
    algorithm: topk_balltree_combined_tree_optimized_parallel_32
  -
    lang: python
    algorithm: topk_balltree_combined_tree_optimized_parallel_16
  -
    lang: python
    algorithm: topk_balltree_combined_tree_optimized_parallel_8
  # -
  #   lang: python
  #   algorithm: topk_balltree_combined_tree_optimized_parallel_4
  # -
  #   lang: python
  #   algorithm: topk_balltree_combined_tree_optimized_parallel_2
  # -
  #   lang: python
  #   algorithm: topk_balltree_combined_tree_optimized_parallel_1
