context:
  prefix: topk_default
  data: cancer_postprocessed_nonegatives_dropduplicates_sample-0.25
  k_ratio: 0.001
  threshold: 0.9
  n_repeat: 3
  n_threads: 1
experiments:
  -
    lang: python
    algorithm: topk_matrix
  -
    lang: python
    algorithm: topk_partition
  -
    lang: python
    algorithm: topk_balltree_combined_tree
  -
    lang: julia
    algorithm: topk_matrix
  # temporarily disable due to runtimes exceeding 7 hours
  -
    lang: r
    algorithm: topk_matrix
