context:
  prefix: topk_parallel
  data: (preeclampsia|pregnancy|cancer_postprocessed_nonegatives_dropduplicates_sample-(0.25|0.50|1.00)|singlecell_postprocessed).*
  # data: (preeclampsia|pregnancy).*
  k_ratio: 0.001
  threshold: 0.9
  n_repeat: 10
  n_threads: 1
  python:
    memory_backend: psutil
experiments:
  -
    lang: python
    algorithm: topk_balltree_combined_tree_optimized_parallel_64
