context:
  prefix: topk_default
  data: singlecell_postprocessed
  k_ratio: 0.001
  threshold: 0.9
  n_repeat: 3
  n_threads: 1
experiments:
  -
    lang: python
    algorithm: topk_balltree_combined_tree
