context:
  prefix: topk_default
  data: (preeclampsia|pregnancy).*
  k_ratio: 0.001
  threshold: 0.9
  n_repeat: 10
  n_threads: 1
experiments:
  -
    lang: python
    algorithm: topk_matrix
  -
    lang: python
    algorithm: topk_partition
  -
    lang: python
    algorithm: topk_balltree_combined_tree
  -
    lang: julia
    algorithm: topk_matrix
  -
    lang: r
    algorithm: topk_matrix
